/*Array method ex*/
x=["pen","pencil","book","bag","scale","eraser","book","desk","chair","table"]
console.log(x)
x.push("inkpen")
console.log(x)
x.pop()
console.log(x)
x.shift()
console.log(x)
console.log(x.includes("desk"))
console.log(x.indexOf("eraser"))
x.reverse()
console.log(x)
x.fill("nipuna")
console.log(x)